### PR TITLE
feat: integrate rich text editor

### PR DESCRIPTION
**Pull request by marianfoo**
Erstes Section mit [macros Rich Text Editor ](https://ui5.sap.com/#/api/sap.fe.macros.RichTextEditorWithMetadata), hier gibt es leider kein Fullscreen.  
Zweite Section mit dem Control [Rich Text Edito](https://ui5.sap.com/#/api/sap.ui.richtexteditor.RichTextEditor)r. Hier gibt es Fullscreen aber da gibt in der Object Page Probleme.
Oder reicht die Größe des Macros?

image

### CODE REVIEW

**Comment by gregorwolf** [comment]
Kann man beim Macro RTE auch Plugins definieren? Das [Autoresize plugin](https://www.tiny.cloud/docs/tinymce/6/autoresize/) würde für die Anforderung am besten passen.

**Comment by marianfoo** [comment]
das control ist noch relativ neu, erst seit 1.117, das heißt die properties sind nicht vorhanden, aber die APIs
https://ui5.sap.com/#/api/sap.fe.macros.RichTextEditorWithMetadata


Das heißt das Plugin Autoresize kann ich mitgeben, aber aktuell bekomme einen Fehler und weiß nicht genau woran das liegt
image

**Comment by gregorwolf** [comment]
Diese Resource ist weder in 1.119.1, 1.119.2 noch in 1.120.0 vorhanden:

Screenshot 2023-11-07 at 07 18 44

Vielleicht kann uns @c-kobo helfen?

**Comment by marianfoo** [comment]
Ich vermute eher einen Bug weil im Namen der Datei ein `undefined` ist. Aber sonst habe ich auch keine ähnliche Datei gefunden die abgefragt wird

**Comment by gregorwolf** [comment]
Vielleicht hat ja auch @MariusFreitag eine Idee.

**Comment by MariusFreitag** [comment]
Hi @gregorwolf and @marianfoo,

Good to see that you are trying out the new building block!

Currently, it does not support adding plugins, but I'm also tagging @nlunets, as he might be able to provide some more details.

Best
Marius

**Comment by marianfoo** [comment]
Hi @MariusFreitag ,
The macros RTE is perfect for the gregor use case, then we don't have to implement the RTE ourselves.
And the APIs are also available for the macros RTE to add plugins.
I just need guidance on which events or hooks I can use to add the plugin agin when it is activated in edit mode.

I also translated my last comment.

**Comment by nlunets** [comment]
Hello @marianfoo, @gregorwolf indeed as Marius said we don't allow to define plugins now.

We decide to switch the RTE based on the visibility of the FormattedText which is controller by the UI model value changing.

So one thing you could do is listen to the `/isEditable` property change on the `ui` model and adjust based on this but it's definitely not as nice as being able to control the plugins property directly.

**Comment by gregorwolf** [comment]
Thank you @nlunets for your response. Will plugins make it to the roadmap? For the current requirement it would also help if the Editor would show by default the resize option in the lower left corner (Check [Full featured demo: Non-Premium Plugins only](https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/). Such a resize option is also shown here in the GitHub comment editor:

Screenshot 2023-11-08 at 07 28 55

Also GitHub does the automatic resizing of the text area which could be achieved with the [Autoresize plugin](https://www.tiny.cloud/docs/tinymce/6/autoresize/).

**Comment by nlunets** [comment]
Supporting the plugins is something that we can consider for sure. 
 For the resize option, I am trying to find the equivalent on the UI5 wrapper but it doesn't seem to be working even if I edit the configuration, have you managed to get it to work with the base UI5 RTE ?

**Comment by marianfoo** [comment]
I have not tried it it yet.
Only with Auto resize plugin, which works.  
Still need to try your suggestion. I hope I can get macros rte control to add the plugin

**Comment by nlunets** [comment]
autoresize works definitely (tried it out quickly), but the resize option seems to do nothing :/

**Comment by marianfoo** [comment]
Same with Fullscreen, I needed to add with the button group, but I don't have a example anymore.  
Maybe try that, see if it works

**Comment by marianfoo** [comment]
@nlunets 
i tried again with your suggestion to listen for the `ui` model.  
Unfortunately this does not work, because the macros RTE is still a `Text` until it is in view.  
You can see in the screenshot i am in edit mode, but the RTE is still macros (see code [here](https://github.com/gregorwolf/bookshop-demo/blob/457754573ef6f05a7de7481119f73ee189f5f109/app/webapp/ordersUI5latest/webapp/ext/ObjectPageExt.controller.js)) so i dont have access to the macros RTE via like `byId('myRichTextEditor')`
Is there any way to know when the macros RTE appears?

image

**Comment by nlunets** [comment]
Just like any other control, there is no way to know that they appear :/

**Comment by marianfoo** [comment]
> Just like any other control, there is no way to know that they appear :/

thought so, was hopeful that i missed something
Thank you for your support!

**Pull request merged**
